name: Container Workflow

on: push

jobs:
  run-in-container:
    runs-on: self-hosted

    # Specify the container image
    container:
      image: node:20

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Display Node.js version
        run: node -v
